# Generated by Django 5.0.6 on 2024-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(default='Sedan', max_length=50),
            preserve_default=False,
        ),
    ]
