# Generated by Django 5.0.6 on 2024-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
    ]
