# Generated by Django 5.0.6 on 2024-05-21 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep'), ('Wagon', 'Wagon')], default='jeep', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{2,49}$', ['first letter uppecase', 'min3', 'max50'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
